
[encoder]
	#How many pattern slots should the Package Recipe Encoder have.
	#Warning: Changing this value when world is running may cause client crashes.
	#Range: 1 ~ 20
	pattern_slots = 20

[packager]
	#How much FE the Packager should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much total FE the Packager should use per operation.
	#Range: > 0
	energy_req = 500
	#How much FE/t maximum the Packager can use.
	#Range: > 0
	energy_usage = 100
	#Should the Packager draw energy from ME systems.
	draw_me_energy = true
	#Should the Packager not require exact inputs when it will not be ambiguous which package to make.
	check_disjoint = true
	#Should the Packager not require exact inputs. Overrides check_disjoint.
	force_disjoint = false

[packager_extension]
	#How much FE the Packager Extension should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much total FE the Packager Extension should use per operation.
	#Range: > 0
	energy_req = 500
	#How much FE/t maximum the Packager Extension can use.
	#Range: > 0
	energy_usage = 100
	#Should the Packager Extension draw energy from ME systems.
	draw_me_energy = true
	#Should the Packager Extension not require exact inputs when it will not be ambiguous which package to make.
	check_disjoint = true
	#Should the Packager Extension not require exact inputs. Overrides check_disjoint.
	force_disjoint = false

[unpackager]
	#How much FE the Unpackager should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much total FE the Unpackager should use per operation.
	#Range: > 0
	energy_usage = 50
	#Should the Unpackager draw energy from ME systems.
	draw_me_energy = true

[crafter]
	#How much FE the Package Crafter should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much total FE the Package Crafter should use per operation.
	#Range: > 0
	energy_req = 500
	#How much FE/t maximum the Package Crafter can use.
	#Range: > 0
	energy_usage = 100
	#Should the Package Crafter draw energy from ME systems.
	draw_me_energy = true

