
#Atomizer
[atomizer]
	#Default: 100000 (100k)
	#Range: > 0
	energyCapacity = 100000
	#Default: 50
	#Range: > 0
	energyPerTick = 5000
	#Default: 100
	#Range: > 1
	ticksPerOperation = 100

#Chemical Combiner
[combiner]
	#Default: 100000 (100k)
	#Range: > 0
	energyCapacity = 100000
	#Default: 200
	#Range: > 0
	energyPerTick = 20000
	#Default: 5
	#Range: > 1
	ticksPerOperation = 5

#Chemical Dissolver
[dissolver]
	#Default: 100000 (100k)
	#Range: > 0
	energyCapacity = 100000
	#Default: 200
	#Range: > 0
	energyPerTick = 10000
	#Default: 8
	#Range: 1 ~ 64
	maxOutputPerTick = 8

#Evaporator
[evaporator]
	#Default: 160
	#Range: > 1
	ticksPerOperation = 160

#Liquifier
[liquifier]
	#Default: 100000 (100k)
	#Range: > 0
	energyCapacity = 100000
	#Default: 50
	#Range: > 0
	energyPerTick = 5000
	#Default: 100
	#Range: > 1
	ticksPerOperation = 100

#Fission
[fission]
	#Default: 100000 (100k)
	#Range: > 0
	energyCapacity = 100000
	#Default: 300
	#Range: > 0
	energyPerTick = 3000
	#Default: 40
	#Range: > 1
	ticksPerOperation = 40

#Fusion
[fusion]
	#Default: 100000 (100k)
	#Range: > 0
	energyCapacity = 100000
	#Default: 300
	#Range: > 0
	energyPerTick = 3000
	#Default: 40
	#Range: > 1
	ticksPerOperation = 40

